name: Daily Launch Hunter

on:
  schedule:
    - cron: "0 */8 * * *"   # اجرای خودکار هر روز 8 ساعت
  workflow_dispatch:       # امکان اجرای دستی

jobs:
  run:
    runs-on: ubuntu-latest   # سیستم عامل اجرا

    steps:
      - uses: actions/checkout@v4   # دریافت کد ریپو

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"    # نسخهٔ پایتون

      - name: Install dependencies
        run: pip install feedparser requests beautifulsoup4
        # کتابخانه‌های لازم برای ProductHunt + BetaList + IndieHackers + HN

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
